module.exports = {
  content: [
    "./index.html",
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  safelist: [
    '!bg-gradient-to-br',
    '!from-yellow-400',
    '!to-orange-500',
    '!text-black',
    '!ring-4',
    '!ring-white/80',
    'animate-pulse',
    '!shadow-lg',
    '!shadow-yellow-500/50',
    '!from-green-500',
    '!to-green-600',
    '!text-white',
    '!shadow-green-500/30',
    '!ring-1',
    '!ring-green-400/50',
    '!from-yellow-400',
    '!to-yellow-500',
    '!text-yellow-900',
    '!shadow-yellow-500/30',
    '!ring-yellow-400/50',
    '!from-purple-500',
    '!to-purple-600',
    '!shadow-purple-500/30',
    '!ring-purple-400/50',
    '!from-gray-600',
    '!to-gray-700',
    '!text-gray-300',
    '!shadow-gray-500/20',
    '!ring-gray-500/30',
  ],
  theme: {
    extend: {
      gridTemplateColumns: {
        '15': 'repeat(15, minmax(0, 1fr))',
      },
      colors: {
        primary: "#182848",
      },
    },
  },
  plugins: [],
}